# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcb28517e5f00086e870910b946fa0ea6ad8683b3add1c2cd5844aeaa1604005a41e2a0fd87278632b85d889aff16474aae3410d13f331f51e240188a96f0b88

test:
  secret_key_base: 159a144af4d5d84d7b1f4ff9c08f911f0de3ca82d1843c3de564b942a9765ad4a17d7f61d283ffe897b046652414e36d3ba54706e7fac436fce2417ec2a8587d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
